#if defined(adapt_include_atom_list)

adapt_def_ns(DC, "http://purl.org/dc/elements/1.1/")
adapt_def_ns(EPUB, "http://www.idpf.org/2007/ops")
adapt_def_ns(EV, "http://www.w3.org/2001/xml-events")
adapt_def_ns(FB2, "http://www.gribuser.ru/xml/fictionbook/2.0")
adapt_def_ns(PRIVATE, "http://www.pyroxy.com/ns/private")
adapt_def_ns(MATHML, "http://www.w3.org/1998/Math/MathML")
adapt_def_ns(NCX, "http://www.daisy.org/z3986/2005/ncx/")
adapt_def_ns(SHADOW, "http://www.pyroxy.com/ns/shadow")
adapt_def_ns(SVG, "http://www.w3.org/2000/svg")
adapt_def_ns(XHTML, "http://www.w3.org/1999/xhtml")
adapt_def_ns(XLINK, "http://www.w3.org/1999/xlink")
adapt_def_ns(XML, "http://www.w3.org/XML/1998/namespace")

adapt_def_qname2(PRIVATE, bogus)
adapt_def_qname2(PRIVATE, column)
adapt_def_qname2(PRIVATE, pseudos)
adapt_def_qname2(PRIVATE, regionid)
adapt_def_qname2(PRIVATE, regions)
adapt_def_qname2(PRIVATE, environment)

adapt_def_qname2(SHADOW, root)
adapt_def_qname2(SHADOW, content)

adapt_def_qname2(XHTML, a)
adapt_def_qname2(XHTML, body)
adapt_def_qname2(XHTML, div)
adapt_def_qname2(XHTML, head)
adapt_def_qname2(XHTML, html)
adapt_def_qname2(XHTML, img)
adapt_def_qname2(XHTML, p)
adapt_def_qname2(XHTML, span)
adapt_def_qname2(XHTML, style)
adapt_def_qname2(XHTML, link)

adapt_def_qname2(XML, id)

adapt_def_name(after)
adapt_def_name(arg0)
adapt_def_name(arg1)
adapt_def_name(arg2)
adapt_def_name(arg3)
adapt_def_name(arg4)
adapt_def_name(arg5)
adapt_def_name(arg6)
adapt_def_name(arg7)
adapt_def_name(auto)
adapt_def_name(avoid)
adapt_def_name(azimuth)
adapt_def_name(background)
adapt_def_name(before)
adapt_def_name(bold)
adapt_def_name(bolder)
adapt_def_name(boolean)
adapt_def_name(border)
adapt_def_name(bottom)
adapt_def_name(caption)
adapt_def_name(ceil)
adapt_def_name(center)
adapt_def_name(ch)
adapt_def_name(charset)
adapt_def_name(cons)
adapt_def_name(color)
adapt_def_name(columns)
adapt_def_name(class)
adapt_def_name(cm)
adapt_def_name(cursor)
adapt_def_name(deg)
adapt_def_name(direction)
adapt_def_name(display)
adapt_def_name(dpcm)
adapt_def_name(dpi)
adapt_def_name(dppx)
adapt_def_name(elevation)
adapt_def_name(em)
adapt_def_name(en)
adapt_def_name(enabled)
adapt_def_name(ex)
adapt_def_name(exclusive)
adapt_def_name(false)
adapt_def_name(floor)
adapt_def_name(footnote)
adapt_def_name(grad)
adapt_def_name(height)
adapt_def_name(href)
adapt_def_name(hsl)
adapt_def_name(hsla)
adapt_def_name(icon)
adapt_def_name(import)
adapt_def_name(inherit)
adapt_def_name(inline)
adapt_def_name(in)
adapt_def_name(italic)
adapt_def_name(kHz)
adapt_def_name(last)
adapt_def_name(left)
adapt_def_name(letterbox)
adapt_def_name(light)
adapt_def_name(lighter)
adapt_def_name(list)
adapt_def_name(max)
adapt_def_name(margin)
adapt_def_name(media)
adapt_def_name(menu)
adapt_def_name(min)
adapt_def_name(mm)
adapt_def_name(ms)
adapt_def_name(namespace)
adapt_def_name(nil)
adapt_def_name(none)
adapt_def_name(normal)
adapt_def_name(nowrap)
adapt_def_name(number)
adapt_def_name(oblique)
adapt_def_name(opacity)
adapt_def_name(orphans)
adapt_def_name(page)
adapt_def_name(padding)
adapt_def_name(pc)
adapt_def_name(pre)
adapt_def_name(pt)
adapt_def_name(px)
adapt_def_name(quotes)
adapt_def_name(rad)
adapt_def_name(rel)
adapt_def_name(rem)
adapt_def_name(required)
adapt_def_name(rex)
adapt_def_name(rgb)
adapt_def_name(rgba)
adapt_def_name(richness)
adapt_def_name(right)
adapt_def_name(s)
adapt_def_name(sqrt)
adapt_def_name(src)
adapt_def_name(static)
adapt_def_name(stress)
adapt_def_name(string)
adapt_def_name(tail)
adapt_def_name(template)
adapt_def_name(top)
adapt_def_name(trace)
adapt_def_name(true)
adapt_def_name(turn)
adapt_def_name(type)
adapt_def_name(typeof)
adapt_def_name(underline)
adapt_def_name(unknown)
adapt_def_name(utilization)
adapt_def_name(visibility)
adapt_def_name(volume)
adapt_def_name(vh)
adapt_def_name(vmin)
adapt_def_name(vmax)
adapt_def_name(vw)
adapt_def_name(width)
adapt_def_name(widows)

adapt_def_name(Hz)

adapt_def_name(SPACE)
adapt_def_name(SIMPLE)
adapt_def_name(INSETS)
adapt_def_name(INSETS_SLASH)
adapt_def_name(COMMA)
adapt_def_name(FONT)

adapt_def_name(HASHCOLOR)
adapt_def_name(POS_INT)
adapt_def_name(POS_NUM)
adapt_def_name(POS_PERCENTAGE)
adapt_def_name(NEGATIVE)
adapt_def_name(ZERO)
adapt_def_name(ZERO_PERCENTAGE)
adapt_def_name(POS_LENGTH)
adapt_def_name(POS_ANGLE)
adapt_def_name(POS_TIME)
adapt_def_name(FREQUENCY)
adapt_def_name(RESOLUTION)
adapt_def_name(URI)
adapt_def_name(IDENT)
adapt_def_name(STRING)

adapt_def_name_str(adapt_footnote_area, "-adapt-footnote-area")
adapt_def_name_str(asterisk, "*")
adapt_def_name_str(background_attachment, "background-attachment")
adapt_def_name_str(background_clip, "background-clip")
adapt_def_name_str(background_color, "background-color")
adapt_def_name_str(background_image, "background-image")
adapt_def_name_str(background_origin, "background-origin")
adapt_def_name_str(background_position, "background-position")
adapt_def_name_str(background_repeat, "background-repeat")
adapt_def_name_str(background_size, "background-size")
adapt_def_name_str(bottom_edge, "bottom-edge")
adapt_def_name_str(border_bottom_color, "border-bottom-color")
adapt_def_name_str(border_bottom_edge, "border-bottom-edge")
adapt_def_name_str(border_bottom_style, "border-bottom-style")
adapt_def_name_str(border_bottom_width, "border-bottom-width")
adapt_def_name_str(border_collapse, "border-collapse")
adapt_def_name_str(border_left_color, "border-left-color")
adapt_def_name_str(border_left_edge, "border-left-edge")
adapt_def_name_str(border_left_style, "border-left-style")
adapt_def_name_str(border_left_width, "border-left-width")
adapt_def_name_str(border_right_color, "border-right-color")
adapt_def_name_str(border_right_edge, "border-right-edge")
adapt_def_name_str(border_right_style, "border-right-style")
adapt_def_name_str(border_right_width, "border-right-width")
adapt_def_name_str(border_spacing, "border-spacing")
adapt_def_name_str(border_top_color, "border-top-color")
adapt_def_name_str(border_top_edge, "border-top-edge")
adapt_def_name_str(border_top_style, "border-top-style")
adapt_def_name_str(border_top_width, "border-top-width")
adapt_def_name_str(break_after, "break-after")
adapt_def_name_str(break_before, "break-before")
adapt_def_name_str(caption_side, "caption-side")
adapt_def_name_str(column_count, "column-count")
adapt_def_name_str(column_fill, "column-fill")
adapt_def_name_str(column_gap, "column-gap")
adapt_def_name_str(column_rule, "column-rule")
adapt_def_name_str(column_width, "column-width")
adapt_def_name_str(comma, ",")
adapt_def_name_str(conflicting_partitions, "conflicting-partitions")
adapt_def_name_str(close_parenthesis, ")")
adapt_def_name_str(empty_cells, "empty-cells")
adapt_def_name_str(epubx_define, "-epubx-define")
adapt_def_name_str(epubx_expr, "-epubx-expr")
adapt_def_name_str(epubx_flow, "-epubx-flow")
adapt_def_name_str(epubx_page_master, "-epubx-page-master")
adapt_def_name_str(epubx_page_template, "-epubx-page-template")
adapt_def_name_str(epubx_partition, "-epubx-partition")
adapt_def_name_str(epubx_partition_group, "-epubx-partition-group")
adapt_def_name_str(epubx_region, "-epubx-region")
adapt_def_name_str(epubx_viewport, "-epubx-viewport")
adapt_def_name_str(epubx_when, "-epubx-when")
adapt_def_name_str(font_size, "font-size")
adapt_def_name_str(font_face, "font-face")
adapt_def_name_str(font_family, "font-family")
adapt_def_name_str(font_style, "font-style")
adapt_def_name_str(font_variant, "font-variant")
adapt_def_name_str(font_weight, "font-weight")
adapt_def_name_str(force_fill, "force-fill")
adapt_def_name_str(flow_from, "flow-from")
adapt_def_name_str(flow_into, "flow-into")
adapt_def_name_str(flow_linger, "flow-linger")
adapt_def_name_str(flow_options, "flow-options")
adapt_def_name_str(flow_priority, "flow-priority")
adapt_def_name_str(has_content, "has-content")
adapt_def_name_str(inline_block, "inline-block")
adapt_def_name_str(left_edge, "left-edge")
adapt_def_name_str(letter_spacing, "letter-spacing")
adapt_def_name_str(line_height, "line-height")
adapt_def_name_str(list_style_image, "list-style-image")
adapt_def_name_str(list_style_position, "list-style-position")
adapt_def_name_str(list_style_type, "list-style-type")
adapt_def_name_str(margin_bottom, "margin-bottom")
adapt_def_name_str(margin_bottom_edge, "margin-bottom-edge")
adapt_def_name_str(margin_left, "margin-left")
adapt_def_name_str(margin_left_edge, "margin-left-edge")
adapt_def_name_str(margin_right, "margin-right")
adapt_def_name_str(margin_right_edge, "margin-right-edge")
adapt_def_name_str(margin_top, "margin-top")
adapt_def_name_str(margin_top_edge, "margin-top-edge")
adapt_def_name_str(margin_after, "margin-after")  // logical after geometric
adapt_def_name_str(margin_before, "margin-before")
adapt_def_name_str(margin_end, "margin-end")
adapt_def_name_str(margin_start, "margin-start")
adapt_def_name_str(max_width, "max_width")
adapt_def_name_str(max_height, "max_height")
adapt_def_name_str(message_box, "message-box")
adapt_def_name_str(min_page_height, "min-page-height")
adapt_def_name_str(min_page_width, "min-page-width")
adapt_def_name_str(open_brace, "{")
adapt_def_name_str(open_parenthesis, "(")
adapt_def_name_str(padding_bottom, "padding-bottom")
adapt_def_name_str(padding_bottom_edge, "padding-bottom-edge")
adapt_def_name_str(padding_left, "padding-left")
adapt_def_name_str(padding_left_edge, "padding-left-edge")
adapt_def_name_str(padding_right, "padding-right")
adapt_def_name_str(padding_right_edge, "padding-right-edge")
adapt_def_name_str(padding_top, "padding-top")
adapt_def_name_str(padding_top_edge, "padding-top-edge")
adapt_def_name_str(page_height, "page-height")
adapt_def_name_str(page_number, "page-number")
adapt_def_name_str(page_width, "page-width")
adapt_def_name_str(percent, "%")
adapt_def_name_str(pitch_range, "pitch-range")
adapt_def_name_str(plus, "+")
adapt_def_name_str(pre_line, "pre-line")
adapt_def_name_str(pre_wrap, "pre-wrap")
adapt_def_name_str(pref_horizontal, "pref-horizontal")
adapt_def_name_str(pref_night_mode, "pref-night-mode")
adapt_def_name_str(required_partitions, "required-partitions")
adapt_def_name_str(right_edge, "right-edge")
adapt_def_name_str(sans_serif, "sans-serif")
adapt_def_name_str(semicolon, ";")
adapt_def_name_str(shape_inside, "shape-inside")
adapt_def_name_str(shape_outside, "shape-outside")
adapt_def_name_str(slash, "/")
adapt_def_name_str(snap_height, "snap-height")
adapt_def_name_str(snap_width, "snap-width")
adapt_def_name_str(small_caption, "small-caption")
adapt_def_name_str(speak_header, "speak-header")
adapt_def_name_str(speak_numeral, "speak-numeral")
adapt_def_name_str(speak_punctuation, "speak-punctuation")
adapt_def_name_str(speech_rate, "speech-rate")
adapt_def_name_str(status_bar, "status-bar")
adapt_def_name_str(text_align, "text-align")
adapt_def_name_str(text_indent, "text-indent")
adapt_def_name_str(text_decoration, "text-decoration")
adapt_def_name_str(text_transform, "text-transform")
adapt_def_name_str(top_edge, "top-edge")
adapt_def_name_str(vertical_rl, "vertical-rl")
adapt_def_name_str(voice_family, "voice-family")
adapt_def_name_str(white_space, "white-space")
adapt_def_name_str(word_spacing, "word-spacing")
adapt_def_name_str(wrap_flow, "wrap-flow")
adapt_def_name_str(writing_mode, "writing-mode")
adapt_def_name_str(z_index, "z-index")

adapt_def_name_str(DC_title, "http://purl.org/dc/terms/title")

#endif
