module.exports = {
  extends: ["stylelint-config-standard-scss"],
  rules: {
    "alpha-value-notation": null,
    "at-rule-empty-line-before": null,
    "color-function-notation": null,
    "color-hex-length": null,
    "declaration-block-no-redundant-longhand-properties": null,
    "declaration-empty-line-before": null,
    "keyframes-name-pattern": null,
    "length-zero-no-unit": null,
    "media-feature-range-notation": null,
    "property-no-vendor-prefix": null,
    "rule-empty-line-before": null,
    "selector-class-pattern": null,
    "selector-id-pattern": null,
    "selector-pseudo-element-colon-notation": null,
    "value-keyword-case": null,
    "value-no-vendor-prefix": null,
    "scss/at-import-no-partial-leading-underscore": null,
    "scss/at-mixin-argumentless-call-parentheses": null,
    "scss/dollar-variable-empty-line-before": null,
    "scss/dollar-variable-pattern": null,
    "scss/double-slash-comment-empty-line-before": null,
    "scss/double-slash-comment-whitespace-inside": null,
    "scss/load-no-partial-leading-underscore": null,
  },
};
